@REM python run.py --dataset adult_cleaned --blackbox_model lr --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_lime_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model lr --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_lime_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model lr --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_lime_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model lr --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_factor_gam_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model lr --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_factor_gam_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model lr --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_factor_gam_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model lr --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_decision_tree_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model lr --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_decision_tree_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model lr --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_lr_decision_tree_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model xgb --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_lime_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model xgb --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_lime_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model xgb --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_lime_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model xgb --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_factor_gam_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model xgb --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_factor_gam_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model xgb --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_factor_gam_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model xgb --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_decision_tree_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model xgb --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_decision_tree_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model xgb --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_xgb_decision_tree_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model rf --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_lime_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model rf --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_lime_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model rf --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_lime_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model rf --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_factor_gam_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model rf --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_factor_gam_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model rf --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_factor_gam_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model rf --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_decision_tree_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model rf --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_decision_tree_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model rf --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_rf_decision_tree_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model nn --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_lime_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model nn --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_lime_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model nn --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_lime_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model nn --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_factor_gam_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model nn --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_factor_gam_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model nn --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_factor_gam_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model nn --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_decision_tree_adult_cleaned 
@REM python run.py --dataset compas_balanced --blackbox_model nn --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_decision_tree_compas_balanced 
@REM python run.py --dataset lsac --blackbox_model nn --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_nn_decision_tree_lsac 

@REM python run.py --dataset adult_cleaned --blackbox_model svm_rbf --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_lime_adult_cleaned 
python run.py --dataset compas_balanced --blackbox_model svm_rbf --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_lime_compas_balanced 
python run.py --dataset lsac --blackbox_model svm_rbf --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_lime_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model svm_rbf --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_factor_gam_adult_cleaned 
python run.py --dataset compas_balanced --blackbox_model svm_rbf --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_factor_gam_compas_balanced 
python run.py --dataset lsac --blackbox_model svm_rbf --explanation_type global --explanation_model factor_gam --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_factor_gam_lsac 
@REM python run.py --dataset adult_cleaned --blackbox_model svm_rbf --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_decision_tree_adult_cleaned 
python run.py --dataset compas_balanced --blackbox_model svm_rbf --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_decision_tree_compas_balanced 
python run.py --dataset lsac --blackbox_model svm_rbf --explanation_type global --explanation_model decision_tree --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/eff_svm_rbf_decision_tree_lsac 

python run.py --dataset adult_cleaned --blackbox_model lr --explanation_type local --explanation_model lime --n_features 10 --model_type JTT --evaluate_val --seed 1 --output_dir ./output/robust_jtt
python run.py --dataset adult_cleaned --blackbox_model lr --explanation_type local --explanation_model lime --n_features 10 --model_type IJTT --evaluate_val --seed 1 --output_dir ./output/robust_ijtt 
@REM python run.py --dataset adult_cleaned --blackbox_model lr --explanation_type local --explanation_model lime --n_features 100 --model_type GroupDRO --evaluate_val --seed 1 --output_dir ./output/robust_gdro 
python run.py --dataset adult_cleaned --blackbox_model lr --explanation_type local --explanation_model lime --n_features 10 --model_type JointDRO --evaluate_val --seed 1 --output_dir ./output/robust_jdro


